# Generated by Django 6.0.3 on 2026-03-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_password_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100)),
                ('cuatrimestre', models.CharField(max_length=50)),
                ('grado_grupo', models.CharField(max_length=20)),
                ('anio', models.IntegerField(default=2026)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('equipo', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio')),
            ],
        ),
    ]
